version = 0.1
[default.deploy.parameters]
stack_name = "anagtosuram-bot-app"
s3_bucket = "tosuri-sam-artifact"
s3_prefix = "anagtosuram-bot"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
image_repositories = []
